name: file_manager
description: File Manager App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^8.1.1
  bloc:

  # Persistent storage
  shared_preferences: ^2.0.15

  # File
  mime_type: ^1.0.0
  path: ^1.8.2
  path_provider: ^2.0.11
  open_file: ^3.2.0

  # Device
  #device_info_plus: ^6.0.0
  device_apps: ^2.2.0
  permission_handler: ^10.2.0
  isolate_handler: ^1.0.2
  platform: ^3.1.0

  # Player
  video_player: ^2.4.7

  # Utils
  intl: ^0.17.0
  percent_indicator: ^4.2.2

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

